on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    name: Build & test
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test



  repo_summary_job:
    runs-on: ubuntu-latest
    name: Write a summary of specified repositories into a Markdown file
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run summary workflow
        uses: ./ 
        id: rsw
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          commit_username: github-actions
          commit_email: github-actions@github.com
          commit_message: Update repository summaries in README
          readme_path: ./example/README.md
          repo_list: hoangvu01/Tetris-Plus-Plus ; hoangvu01/not_here 
          image_folder: assets/
          lang_bar_height: 12
          lang_bar_width: 200